#Theory Quetions

1.  What are data structures, and why are they important?
*  Data structure is a way to organizing & storing data, so that it can be accessed & manipulated efficiently.They help manage large amounts of data in a way that allows for quick search, insertion, deletion, and updating.
*  They're important because they enable efficient problem-solving and are the foundation of algorithms, making programs faster and more efficient.

2.  Explain the difference between mutable and immutable data types with examples.
*  Mutable data types can be changed after they're created, while immutable data types cannot be changed once created.
*  Mutable Data types
  *  list > my_list = [1, 2, 3] > We can do my_list[0] = 10
*  Immutable Data types
  *  tuple > my_tuple = (1, 2, 3) > We can't change my_tuple[0]
  *  str > name = "pwskills" > We can't change name[0]

3. What are the main differences between lists and tuples in Python
*  List
  * We create a list using square brackets [].
  * Lists are mutable, which means we can modify a list's elements after creating it.
*  Tuple
  * We create a tuple using parentheses ().
  * Tuples are immutable, which means we cannot modify a tuple's elements after creating it.

4.  Describe how dictionaries store data
*  It is a data structure that stores data as key-value pairs.
*  Keys are unique and immutable.
* Dictionaries maintain the order of insertion, which means if we iterate over a dictionary, the items will be returned in the order they were inserted.

5. Why might you use a set instead of a list in Python
*  A set does not contain any duplicate values, but a list can.
*  In a scenario where we don't want any duplicate values, we can use a set.

6.  What is a string in Python, and how is it different from a list
*  A string is a sequence of characters used for representing and manipulating textual data.
*  Strings are immutable, but lists are mutable. A string contains only characters, while a list can hold different kinds of data types.

7. How do tuples ensure data integrity in Python
*  Tuples are immutable, which means their elements cannot be changed after they are created. This immutability is the key to how tuples ensure data integrity.

8.  What is a hash table, and how does it relate to dictionaries in Python?
*  A hash table is a data structure that stores data using a key and computes an index using a hash function.
*  In Python, dictionaries are implemented using hash tables to store key-value pairs efficiently.

9. Can lists contain different data types in Python?
*  Yes list can contain different data types.
*  Example my_list = [1,2,3,"pwskills",True,5+10j,False,None]

10. Explain why strings are immutable in Python.
*  Strings are immutable in Python because once we create a string, we cannot modify its elements.
*  Example: my_str = "pwskills" → my_str[0] = "A" it will cause an error.

11. What advantages do dictionaries offer over lists for certain tasks?
*  Dictionaries allow us to store data in a key-value form, which is useful when we want to organize data meaningfully.
*  Example: {"name": "Soumya", "course": "Data Analytics", "institution": "Pwskills"}
* Lists only allow us to store data in a sequential manner.
* Example: ["name", "Soumya", "course", "Data Analytics", "institution", "Pwskills"]

12.  Describe a scenario where using a tuple would be preferable over a list
*  In a scenario where we do not want to modify our elements, we can use a tuple data structure because tuples are immutable.

13.  How do sets handle duplicate values in Python?
*  A set does not allow duplicate values.
*  Example: my_set = {1, 2, 2, 3, 4, 4, 5}
It will omit all the duplicate values and give us something like {1, 2, 3, 4, 5}.

14.  How does the “in” keyword work differently for lists and dictionaries?
*  In a list, the “in” keyword checks if a value exists as an element in the list.
*  Example: 3 in [1, 2, 3, 4] -> True
*  In a dictionary, the “in” keyword checks if a key exists in the dictionary.
*  Example: 'name' in {'name': 'John', 'age': 30} -> True

15. Can you modify the elements of a tuple? Explain why or why not.
* No we can not modify the elements of a tuple, because tuples are an immutable data structure in Python & do not allow item assignments.
* _tup = (1,2,3,4) _tup[0] = 10 it will cause an error.

16.  What is a nested dictionary, and give an example of its use case
* A nested dictionary means a dictionary inside another dictionary.
* Example: my_dict = {
    "name": "Soumya Ranjan Barik",
    "email": "soumyarb2021@gmail.com",
    "contact": 1234567890,
    "address": {
        "city": "Baripada, 757001",
        "dist": "Mayurbhanj",
        "state": "Odisha"
    }
}
* Nested dictionaries are useful when we need to store hierarchical or complex data. For example, when representing a person's details where the address has its own subfields (city, district, state).

17.  Describe the time complexity of accessing elements in a dictionary
*  The time complexity of accessing an element in a dictionary is O(1) on average, meaning it takes constant time.
*  This is because dictionaries in Python are implemented using hash tables, allowing for quick lookups by key.

18. In what situations are lists preferred over dictionaries?
*  When order matters: Lists maintain the order of elements, which is useful when we need to preserve the sequence.
* When we need to store multiple values: Lists are ideal when we have a collection of items and we don’t need to associate them with unique keys.

19.  Why are dictionaries considered unordered, and how does that affect data retrieval?
* Dictionaries are considered unordered because the keys are hashed, and their order isn't guaranteed. This means the order of elements may change, but data can still be retrieved efficiently using the key.
* Since Python 3.7, dictionaries maintain the insertion order, meaning the order in which items are added is maintained.

20. Explain the difference between a list and a dictionary in terms of data retrieval.
*  List: Data is retrieved by index, which is an integer position in the sequence. The time complexity for retrieving an element is O(1) for direct access, but requires knowing the index.
* Dictionary: Data is retrieved by key, which can be any immutable type. The time complexity for retrieving a value is O(1) on average due to the hash-based implementation.

#Practical Questions

In [1]:
# 1.Write a code to create a string with your name and print it.
name = "Soumya Ranjan Barik"
print(name)

Soumya Ranjan Barik

In [2]:
# 2.Write a code to find the length of the string "Hello World"
text = "Hello World"
print(len(text))

11

In [3]:
# 3.Write a code to slice the first 3 characters from the string "Python Programming.
text = "Python Programming"
print(text[0:3])

Pyt

In [4]:
# 4.Write a code to convert the string "hello" to uppercase.
text = "hello"
print(text.upper())

HELLO

In [7]:
# 5.Write a code to replace the word "apple" with "orange" in the string "I like apple"
text = "I like apple."
print(text.replace("apple","orange"))

I like orange.

In [9]:
# 6.Write a code to create a list with numbers 1 to 5 and print it
my_list = [1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]

In [10]:
# 7.Write a code to append the number 10 to the list [1, 2, 3, 4].
my_list = [1,2,3,4]
my_list.append(10)
print(my_list)

[1, 2, 3, 4, 10]

In [11]:
# 8.Write a code to remove the number 3 from the list [1, 2, 3, 4, 5]
my_list = [1,2,3,4,5]
my_list.remove(3)
print(my_list)

[1, 2, 4, 5]

In [12]:
# 9.Write a code to access the second element in the list ['a', 'b', 'c', 'd'].
my_list = ['a', 'b', 'c', 'd']
print(my_list[1])

b

In [13]:
# 10.Write a code to reverse the list [10, 20, 30, 40, 50].
my_list = [10, 20, 30, 40, 50]
print(my_list[::-1])

[50, 40, 30, 20, 10]

In [14]:
# 11.Write a code to create a tuple with the elements 100, 200, 300 and print it.
my_tup = (100,200,300)
print(my_tup)

(100, 200, 300)

In [15]:
# 12.Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow').
my_tup = ('red', 'green', 'blue', 'yellow')
print(my_tup[-2])

blue

In [16]:
# 13.Write a code to find the minimum number in the tuple (10, 20, 5, 15).
my_tup = (10, 20, 5, 15)
print(min(my_tup))

5

In [17]:
# 14. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').
my_tup = ('dog', 'cat', 'rabbit')
print(my_tup.index("cat"))

1

In [18]:
# 15.Write a code to create a tuple containing three different fruits and check if "kiwi" is in it.
my_tup = ("apple", "banana", "cherry")
if "kiwi" in my_tup:
  print("kiwi is in the tuple")
else:
  print("kiwi is not in the tuple")

kiwi is not in the tuple

In [19]:
# 16.Write a code to create a set with the elements 'a', 'b', 'c' and print it.
my_set = {'a','b','c'}
print(my_set)

{'a', 'c', 'b'}

In [20]:
# 17.Write a code to clear all elements from the set {1, 2, 3, 4, 5}.
my_set = {1, 2, 3, 4, 5}
my_set.clear()
print(my_set)

set()

In [21]:
# 18.Write a code to remove the element 4 from the set {1, 2, 3, 4}.
my_set = {1,2,3,4}
my_set.remove(4)
print(my_set)

{1, 2, 3}

In [24]:
# 19.Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}.
_set1 = {1,2,3}
_set2 = {3,4,5}
# union of two set
_set3 = _set1 | _set2
print(_set3)

{1, 2, 3, 4, 5}

In [25]:
# 20.Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}.
_set1 = {1,2,3}
_set2 = {2,3,4}
# intersection of two set
_set3 = _set1 & _set2
print(_set3)

{2, 3}

In [26]:
# 21.Write a code to create a dictionary with the keys "name", "age", and "city", and print it.
my_dict = {"name": "Soumya", "age": 21, "city": "Baripada"}
print(my_dict)

{'name': 'Soumya', 'age': 21, 'city': 'Baripada'}

In [27]:
# 22.Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}.
my_dict = {'name': 'John', 'age': 25}
my_dict["country"] = "USA"
print(my_dict)

{'name': 'John', 'age': 25, 'country': 'USA'}

In [28]:
# 23.Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}.
my_dict = {'name': 'Alice', 'age': 30}
print(my_dict['name'])

Alice

In [30]:
# 24.Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}.
my_dict = {'name': 'Bob', 'age': 22, 'city': 'New York'}
del my_dict['age']
print(my_dict)

{'name': 'Bob', 'city': 'New York'}

In [31]:
# 25.Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}.
my_dict = {'name': 'Alice', 'city': 'Paris'}
if 'city' in my_dict:
  print("city is in the dictionary")
else:
  print("city is not in the dictionary")

city is in the dictionary

In [32]:
# 26.Write a code to create a list, a tuple, and a dictionary, and print them all.
my_list = [1,2,3,4,5]
my_tup = (1,2,3,4,5)
my_dict = {"name": "Soumya", "age": 21, "city": "Baripada"}
print(my_list)
print(my_tup)
print(my_dict)

[1, 2, 3, 4, 5]
(1, 2, 3, 4, 5)
{'name': 'Soumya', 'age': 21, 'city': 'Baripada'}

In [34]:
# 27.Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the result.(replaced).
import random
my_list = [random.randint(1,100) for i in range(5)]
my_list.sort()
print(my_list)

[36, 57, 66, 92, 93]

In [37]:
# 28.Write a code to create a list with strings and print the element at the third index.
my_list = ["apple", "banana", "cherry", "date", "orange"]
print(my_list[3])

date

In [38]:
# 29.Write a code to combine two dictionaries into one and print the result.
user_details = {"name":"Soumya Ranjan Barik","email":"soumyarb2021@gmail.com","contact":7978943453}
course_details = {"course":"Data Analytics","institution":"Pwskills","duration":"6 Months"}
user_details.update(course_details)
print(user_details)

{'name': 'Soumya Ranjan Barik', 'email': 'soumyarb2021@gmail.com', 'contact': 7978943453, 'course': 'Data Analytics', 'institution': 'Pwskills', 'duration': '6 Months'}

In [39]:
# 30.Write a code to convert a list of strings into a set.
_list = ["apple","banana","apple","mango","kiwi","blueberry","mango"]
_set = set(_list)
print(_set)

{'blueberry', 'banana', 'kiwi', 'mango', 'apple'}